"""Bridge to the eval harness: batch manifest → harness ``manifest.toml``.

The harness loader (``fluidvoice.evalharness.manifest``) is the
unchangeable contract (owned by another workstream): TOML, one
``[[cases]]`` table per case, required keys id/audio/reference_text/
language/tags/expected_guard/license/source, unknown keys tolerated.
Provenance keys (speaker, taxonomy, mic_class, …) ride along as the
extra keys the spec §1 documents; a test pins that the exported file
loads cleanly through the real harness loader.
"""
from __future__ import annotations

import os
from datetime import date
from pathlib import Path

from .model import BatchManifest, Case
from .tomlout import dump_case_table

#: Extra provenance keys exported per case (spec §1 + consent/split
#: traceability); all optional in the batch, emitted only when set.
_EXTRA_KEYS = ("speaker", "taxonomy", "mic_class", "mic_model", "snr_db",
               "environment", "session_date", "accent", "consent_ref")


def _source_line(batch: BatchManifest, case: Case) -> str:
    when = case.session_date or batch.created
    return (f"recorded session {when} via {batch.recorder.name} "
            f"{batch.recorder.version} (batch {batch.batch}; backend "
            f"{batch.recorder.backend.get('type', '?')})")


def _case_row(batch: BatchManifest, case: Case, audio_rel: str) -> dict:
    row: dict[str, object] = {
        "id": case.id,
        "audio": audio_rel,
        "reference_text": case.reference_text or "",
        "language": case.language,
        "tags": list(case.tags),
        "expected_guard": case.expected_guard,
        "license": case.effective_license(batch.license),
        "source": _source_line(batch, case),
    }
    extras: dict[str, object] = {
        "speaker": case.speaker,
        "taxonomy": case.taxonomy,
        "mic_class": case.mic_class,
        "mic_model": case.mic_model or None,
        "snr_db": case.snr_db,
        "environment": case.environment or None,
        "session_date": case.session_date or None,
        "accent": case.accent or None,
        "consent_ref": case.consent_ref
        or (batch.speaker(case.speaker).consent_ref if case.speaker
            and batch.speaker(case.speaker) else None),
    }
    for key in _EXTRA_KEYS:
        v = extras[key]
        if v is not None and v != "":
            row[key] = v
    return row


def export_harness_manifest(
    batch: BatchManifest,
    out_path: Path | None = None,
    *,
    include_planned: bool = False,
) -> Path:
    """Write the harness-loadable TOML manifest; returns its path.

    Only ``recorded`` cases export by default (planned ones have no
    audio/transcript). ``out_path`` defaults to ``manifest.toml`` next
    to the batch manifest — audio paths stay valid because they are
    re-relativized against wherever the export lands.
    """
    out_path = Path(out_path) if out_path else batch.path.parent / \
        "manifest.toml"
    out_dir = out_path.resolve().parent
    out_dir.mkdir(parents=True, exist_ok=True)

    cases = [c for c in batch.cases
             if include_planned or c.status == "recorded"]
    if not cases:
        raise ValueError(
            f"{batch.path}: nothing to export — no recorded cases "
            "(pass include_planned=True only for harness smoke tests)")

    header = (
        "# Generated by `python -m scripts.corpus export` from "
        f"{batch.path.name} (batch {batch.batch!r}) on "
        f"{date.today().isoformat()}.\n"
        "# Do not edit by hand — regenerate from the batch manifest.\n"
        "# Private corpus: this file and the audio stay outside git "
        "(docs/eval/README.md §Private corpora).\n\n"
    )
    chunks = [header]
    for case in cases:
        audio_abs = batch.resolve_audio(case)
        audio_rel = _relativize(audio_abs, out_dir)
        chunks.append(dump_case_table(_case_row(batch, case, audio_rel)))
        chunks.append("\n")
    out_path.write_text("".join(chunks), encoding="utf-8")
    return out_path


def _relativize(audio_abs: Path, out_dir: Path) -> str:
    if audio_abs.is_relative_to(out_dir):
        return audio_abs.relative_to(out_dir).as_posix()
    return os.path.relpath(audio_abs, out_dir).replace(os.sep, "/")
